name: measure_temp
channels:
  - conda-forge
dependencies:
  - python==3.7
  - ipython>=7
  - jupyterlab>=3
  - black
  - isort
  - mypy
  - versioneer
  - pip>=22
  - pre-commit
  - pytest>=7
  - pip:
    - pysensors  # not the sklearn pkg
