name: measure_temp
channels:
  - conda-forge
dependencies:
  - python=3.7
  - ipython>=7
  - jupyterlab>=3
  - black
  - isort
  - mypy
  - versioneer
  - pip>=22
  - pre-commit
  - pytest>=7
  - click>=8
  - pip:
    - pysensors==0.0.4  # not the sklearn pkg
